package bsep.integration.predefined;

   import com.tim9.bolnica.model.Log;
   import com.tim9.bolnica.model.AdminAlarm;
   import com.tim9.bolnica.enums.LogSeverity;
   import java.util.Date;
   

   rule "Error log appeared"
       when
           $log: Log($id: id, log.getSeverity() == LogSeverity.ERROR)
           not(AdminAlarm(logId == $id))
       then
           System.out.println("Error log appeared");
           AdminAlarm alarm = new AdminAlarm(null, $id, new Date(), $log.getMessage());
           insert(alarm);
   end
   