package com.tim9.bolnica.enums;

public enum LogFacility {
	KERN, USER, MAIL, DAEMON, AUTH, SYSLOG, LPR, NEWS, UUCP, SOLARISCRON, AUTHPRIV, FTP, NTP, CONSOLE, SECURITY, CRON, LOCAL0, LOCAL1, LOCAL2, LOCAL3, LOCAL4 ,LOCAL5, LOCAL6, LOCAL7
}
