package sbnz.integracija.admin

import java.util.Date;
import com.tim9.bolnica.model.*;
import com.tim9.bolnica.util.BlackListIpAddresses;

rule "Connection from blacklisted IP address"
    when
        $log: Log($id: id, 
            $ip: ip,
            ip memberOf BlackListIpAddresses.blackList    
        )
        not (AdminAlarm(logId == $id))
    then
    	System.out.println("Connection from blacklisted IP adress");
        insert(new AdminAlarm(null, $id, new Date(), "Connection from blacklisted IP address " + $ip));
end
   