package sbnz.integracija.admin

import com.tim9.bolnica.model.*;
import com.tim9.bolnica.enums.*;
import java.util.Date;
   

rule "DoS attack"
    when
        Log($id: id, $m: message, $ip: ip, message.contains("Requested resource"))
        $alarms: ArrayList() from collect( AdminAlarm())
        $no: Number(intValue > 15) from accumulate(
            $log : Log($id2: id, ip == $ip, message == $m)
            over window:time(1m),
            init (int count = 0;),
            action (
                int c = 0;
                for(Object o : $alarms) {
                    AdminAlarm a = (AdminAlarm) o;
                    if (a.getLogId() == $id2 && a.getMessage().contains("DOS ATTACK")) {
                        c += 1;
                        break;
                    }
                }
                if (c == 0) {
                    count += 1;
                }
            ),
            result (count)
        )
        not(AdminAlarm(logId == $id))
    then
        System.out.println("DoS attack");
        AdminAlarm alarm = new AdminAlarm(null, $id, new Date(), "DOS ATTACK - " + $m);
        insert(alarm);
end